### ISSUE TITLE
MSI: Add Chocolatey package

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#12] opened 2020-03-26 06:09 UTC
Chocolatey is a modern package management system (like apt or yum on GNU/Linux) for Windows: https://chocolatey.org/

Most packages for this system is implemeted as a wrapper of an original installer (.msi or .exe).
I'm also planning to use same way to implement td-agent package for it.

**Comment by ashie** [comment] 2020-05-22 05:26
FYI: Microsoft unveils a new package management system: https://github.com/microsoft/winget-cli

**Comment by cosmo0920** [comment] 2020-08-05 05:08
Currently, executables of winget is not provided but the package definition syntax is very easy.
cf.) https://github.com/microsoft/winget-pkgs/blob/6c25507a41ac82587513ae093e0e33d93c235858/manifests/PuppetLabs/puppet/3.8.7.0.yaml

**Comment by cosmo0920** [comment] 2020-08-05 08:30
winget provides CLI tool to generate manifest.
I tested it and it generated the following manifest for td-agent:

```yaml
Id: TreasureData.TDAgent
Version: 4.0.0
Name: TD-Agent
Publisher: Treasure Data Inc.
License: Apache Lincense 2.0
LicenseUrl: https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/LICENSE
AppMoniker: td-agent
Tags: fluentd, logging
Description: Treasure Agent: A data collector for Treasure Data
Homepage: https://www.fluentd.org
Installers:
  - Arch: x64
    Url: http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.0.0-x64.msi
    Sha256: 752DA24B7B4C39C48F3EE66A87A109FC97C7627BAFFD63BD95A5D193296322F8
    InstallerType: msi
```

**Comment by cosmo0920** [comment] 2020-08-05 08:32
I think that creating winget package is easier than creating chocolatey package.

**Comment by cosmo0920** [comment] 2020-08-05 09:15
I'd confirmed that the following manifest can proceed td-agent installation:

```yaml
Id: TreasureData.TDAgent
Version: 4.0.0
Name: TD-Agent
Publisher: Treasure Data Inc.
License: Apache Lincense 2.0
LicenseUrl: https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/LICENSE
AppMoniker: td-agent
Tags: fluentd, logging
Description: "Treasure Agent: A data collector for Treasure Data"
Homepage: https://www.fluentd.org
Installers:
  - Arch: x64
    Url: http://packages.treasuredata.com.s3.amazonaws.com/4/windows/td-agent-4.0.0-x64.msi
    Sha256: 752DA24B7B4C39C48F3EE66A87A109FC97C7627BAFFD63BD95A5D193296322F8
    InstallerType: msi
    Switches:
      Silent: "/quiet"
      SilentWithProgress: "/quiet /passive"
```

But we should this task after td-agent 4.0.1 is released. Because td-agent 4.0.0 has a pitfall to prevent C extension building due to lack of dll.a which is one of the needed component for building C extension with MSYS2.

**Comment by cosmo0920** [comment] 2020-08-06 05:00
I'd tried to register td-agent v3.8.0 package on winget-pkgs repository.
https://github.com/microsoft/winget-pkgs/pull/2908
td-agent 4.0.0 has a putfall for now. It is reasonable to register td-agent v3.8.0 for now.

**Comment by cosmo0920** [comment] 2020-08-06 07:20
I'd also reported incorrect Smart Screen detection for td-agent v3.8.0:
https://www.microsoft.com/en-us/wdsi/submission/94b56dc5-d0dd-4713-86cc-d965ffbe6e75
I'll report this detection for td-agent v4.0.0.

**Comment by cosmo0920** [comment] 2020-08-07 08:04
I'd also reported as RFP for td-agent 3.8.0-0:
https://github.com/chocolatey-community/chocolatey-package-requests/issues/872

**Comment by cosmo0920** [comment] 2020-08-10 03:56
td-agent 3.8.0-0 package has been landed in https://github.com/microsoft/winget-pkgs/pull/2908.

**Comment by cosmo0920** [comment] 2020-08-20 08:23
I'd registered td-agent 4.0.1 package in https://github.com/microsoft/winget-pkgs/pull/3153.

**Comment by cosmo0920** [comment] 2020-08-24 02:30
td-agent 4.0.1 package has been landed in https://github.com/microsoft/winget-pkgs/pull/3153.

**Comment by cosmo0920** [comment] 2020-08-25 05:07
td-agent v4.0.1 Request For Package is registered in https://github.com/chocolatey-community/chocolatey-package-requests/issues/884.

**Comment by cosmo0920** [comment] 2020-09-23 08:18
We can't send a PR to create community packages on Chocolatey.
We'd already registered winget packages as https://github.com/microsoft/winget-pkgs/pull/2908 and https://github.com/microsoft/winget-pkgs/pull/3153.
Closing.

**Closed by cosmo0920** 2020-09-23 08:18 UTC
Labels: Windows, enhancement
